In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from matpowercaseframes import CaseFrames

In [3]:
CASE_NAME = "case9.m"

In [4]:
cf = CaseFrames(CASE_NAME)
cf.infer_numpy()
cf.bus

,BUS_I,BUS_TYPE,PD,QD,GS,BS,BUS_AREA,VM,VA,BASE_KV,ZONE,VMAX,VMIN
1,1,3,0,0,0,0,1,1,0,345,1,1.1,0.9
2,2,2,0,0,0,0,1,1,0,345,1,1.1,0.9
3,3,2,0,0,0,0,1,1,0,345,1,1.1,0.9
4,4,1,0,0,0,0,1,1,0,345,1,1.1,0.9
5,5,1,90,30,0,0,1,1,0,345,1,1.1,0.9
6,6,1,0,0,0,0,1,1,0,345,1,1.1,0.9
7,7,1,100,35,0,0,1,1,0,345,1,1.1,0.9
8,8,1,0,0,0,0,1,1,0,345,1,1.1,0.9
9,9,1,125,50,0,0,1,1,0,345,1,1.1,0.9

In [5]:
cf_pu = cf.to_pu()
cf_pu.bus

,BUS_I,BUS_TYPE,PD,QD,GS,BS,BUS_AREA,VM,VA,BASE_KV,ZONE,VMAX,VMIN
1,1,3,0.00,0.00,0.0,0.0,1,1,0.0,345,1,1.1,0.9
2,2,2,0.00,0.00,0.0,0.0,1,1,0.0,345,1,1.1,0.9
3,3,2,0.00,0.00,0.0,0.0,1,1,0.0,345,1,1.1,0.9
4,4,1,0.00,0.00,0.0,0.0,1,1,0.0,345,1,1.1,0.9
5,5,1,0.90,0.30,0.0,0.0,1,1,0.0,345,1,1.1,0.9
6,6,1,0.00,0.00,0.0,0.0,1,1,0.0,345,1,1.1,0.9
7,7,1,1.00,0.35,0.0,0.0,1,1,0.0,345,1,1.1,0.9
8,8,1,0.00,0.00,0.0,0.0,1,1,0.0,345,1,1.1,0.9
9,9,1,1.25,0.50,0.0,0.0,1,1,0.0,345,1,1.1,0.9